from social_media_post_agent.constants_for_image import config

GEMINI_MODEL = "gemini-2.0-flash"
THUMBNAIL_IMAGE_SIZE = config.THUMBNAIL_IMAGE_SIZE
IMAGE_ROOT_DIR = config.IMAGE_ROOT_DIR
REFERENCE_IMAGES_DIR = config.REFERENCE_IMAGES_DIR
THUMBNAIL_ASSETS_DIR = config.THUMBNAIL_ASSETS_DIR
GENERATED_THUMBNAILS_DIR = config.GENERATED_THUMBNAILS_DIR